04-May-22 17:48:34 - DEBUG - <module>:18 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList
04-May-22 17:48:34 - DEBUG - <module>:20 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList
04-May-22 17:48:34 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
04-May-22 18:04:35 - INFO - getCode:60 - Querying for code
04-May-22 18:04:35 - INFO - _log:224 - 127.0.0.1 - - [04/May/2022 18:04:35] "GET /?error HTTP/1.1" 200 -
04-May-22 18:04:46 - INFO - getCode:60 - Querying for code
04-May-22 18:04:46 - INFO - _log:224 - 127.0.0.1 - - [04/May/2022 18:04:46] "GET /?errorhseugabij=1 HTTP/1.1" 200 -
04-May-22 18:08:13 - DEBUG - <module>:18 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList
04-May-22 18:08:13 - DEBUG - <module>:20 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList
04-May-22 18:08:13 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
05-May-22 16:07:48 - DEBUG - <module>:18 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:07:48 - DEBUG - <module>:20 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:07:48 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
05-May-22 16:08:13 - INFO - getCode:60 - Querying for code
05-May-22 16:08:13 - INFO - getCode:63 - Successfully retrieved code
05-May-22 16:08:13 - INFO - getCode:66 - Querying for access token
05-May-22 16:08:13 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
05-May-22 16:08:14 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/oauth/token HTTP/1.1" 200 None
05-May-22 16:08:14 - INFO - getCode:70 - Successfully retrieved access token using code
05-May-22 16:08:14 - INFO - getCode:77 - Querying for database ID
05-May-22 16:08:14 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
05-May-22 16:08:15 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/search HTTP/1.1" 200 None
05-May-22 16:08:15 - INFO - getCode:80 - Database ID retrieved
05-May-22 16:08:15 - ERROR - log_exception:1455 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 85, in getCode
    addToDatabase(databaseFile, tokenDetails, database_id)
TypeError: addToDatabase() takes 2 positional arguments but 3 were given
05-May-22 16:08:15 - INFO - _log:224 - 127.0.0.1 - - [05/May/2022 16:08:15] "[35m[1mGET /?code=9436158a-3888-42dc-b8d5-0f32f071324d&state= HTTP/1.1[0m" 500 -
05-May-22 16:08:43 - DEBUG - <module>:18 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:08:43 - DEBUG - <module>:20 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:08:43 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
05-May-22 16:08:47 - INFO - getCode:60 - Querying for code
05-May-22 16:08:47 - INFO - getCode:63 - Successfully retrieved code
05-May-22 16:08:47 - INFO - getCode:66 - Querying for access token
05-May-22 16:08:47 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
05-May-22 16:08:49 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/oauth/token HTTP/1.1" 400 25
05-May-22 16:08:49 - INFO - getCode:70 - Successfully retrieved access token using code
05-May-22 16:08:49 - INFO - getCode:77 - Querying for database ID
05-May-22 16:08:49 - ERROR - getCode:82 - Could not retrieve database ID
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 79, in getCode
    response = requests.post(databaseIDurl, headers= {"Notion-Version": "2022-02-22", "Authorization": "Bearer " + token},  data=params)
TypeError: can only concatenate str (not "NoneType") to str
05-May-22 16:08:49 - ERROR - log_exception:1455 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 83, in getCode
    parsedResponse = response.json()
UnboundLocalError: local variable 'response' referenced before assignment
05-May-22 16:08:49 - INFO - _log:224 - 127.0.0.1 - - [05/May/2022 16:08:49] "[35m[1mGET /?code=9436158a-3888-42dc-b8d5-0f32f071324d&state= HTTP/1.1[0m" 500 -
05-May-22 16:08:58 - INFO - getCode:60 - Querying for code
05-May-22 16:08:58 - INFO - getCode:63 - Successfully retrieved code
05-May-22 16:08:58 - INFO - getCode:66 - Querying for access token
05-May-22 16:08:58 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
05-May-22 16:08:59 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/oauth/token HTTP/1.1" 400 25
05-May-22 16:08:59 - INFO - getCode:70 - Successfully retrieved access token using code
05-May-22 16:08:59 - INFO - getCode:77 - Querying for database ID
05-May-22 16:08:59 - ERROR - getCode:82 - Could not retrieve database ID
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 79, in getCode
    response = requests.post(databaseIDurl, headers= {"Notion-Version": "2022-02-22", "Authorization": "Bearer " + token},  data=params)
TypeError: can only concatenate str (not "NoneType") to str
05-May-22 16:08:59 - ERROR - log_exception:1455 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 83, in getCode
    parsedResponse = response.json()
UnboundLocalError: local variable 'response' referenced before assignment
05-May-22 16:08:59 - INFO - _log:224 - 127.0.0.1 - - [05/May/2022 16:08:59] "[35m[1mGET /?code=9436158a-3888-42dc-b8d5-0f32f071324d HTTP/1.1[0m" 500 -
05-May-22 16:09:24 - INFO - _log:224 - 127.0.0.1 - - [05/May/2022 16:09:24] "[33mGET /code=9436158a-3888-42dc-b8d5-0f32f071324d&state= HTTP/1.1[0m" 404 -
05-May-22 16:09:47 - INFO - getCode:60 - Querying for code
05-May-22 16:09:47 - INFO - _log:224 - 127.0.0.1 - - [05/May/2022 16:09:47] "GET / HTTP/1.1" 200 -
05-May-22 16:10:04 - INFO - getCode:60 - Querying for code
05-May-22 16:10:04 - INFO - getCode:63 - Successfully retrieved code
05-May-22 16:10:04 - INFO - getCode:66 - Querying for access token
05-May-22 16:10:04 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
05-May-22 16:10:05 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/oauth/token HTTP/1.1" 400 25
05-May-22 16:10:05 - INFO - getCode:70 - Successfully retrieved access token using code
05-May-22 16:10:05 - INFO - getCode:77 - Querying for database ID
05-May-22 16:10:05 - ERROR - getCode:82 - Could not retrieve database ID
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 79, in getCode
    response = requests.post(databaseIDurl, headers= {"Notion-Version": "2022-02-22", "Authorization": "Bearer " + token},  data=params)
TypeError: can only concatenate str (not "NoneType") to str
05-May-22 16:10:05 - ERROR - log_exception:1455 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 83, in getCode
    parsedResponse = response.json()
UnboundLocalError: local variable 'response' referenced before assignment
05-May-22 16:10:05 - INFO - _log:224 - 127.0.0.1 - - [05/May/2022 16:10:05] "[35m[1mGET /?code=9436158a-3888-42dc-b8d5-0f32f071324d&state= HTTP/1.1[0m" 500 -
05-May-22 16:25:52 - INFO - getCode:60 - Querying for code
05-May-22 16:25:52 - INFO - getCode:63 - Successfully retrieved code
05-May-22 16:25:52 - INFO - getCode:66 - Querying for access token
05-May-22 16:25:52 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
05-May-22 16:25:54 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/oauth/token HTTP/1.1" 200 None
05-May-22 16:25:54 - INFO - getCode:70 - Successfully retrieved access token using code
05-May-22 16:25:54 - INFO - getCode:77 - Querying for database ID
05-May-22 16:25:54 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
05-May-22 16:25:56 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/search HTTP/1.1" 200 None
05-May-22 16:25:56 - INFO - getCode:80 - Database ID retrieved
05-May-22 16:25:56 - ERROR - log_exception:1455 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 85, in getCode
    addToDatabase(databaseFile, tokenDetails, database_id)
TypeError: addToDatabase() takes 2 positional arguments but 3 were given
05-May-22 16:25:56 - INFO - _log:224 - 127.0.0.1 - - [05/May/2022 16:25:56] "[35m[1mGET /?code=84fa5364-486f-4494-9b58-ba9b4efe23d7&state= HTTP/1.1[0m" 500 -
05-May-22 16:30:58 - DEBUG - <module>:18 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:30:58 - DEBUG - <module>:20 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:30:58 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
05-May-22 16:32:30 - DEBUG - <module>:18 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:32:30 - DEBUG - <module>:20 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
05-May-22 16:32:30 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
06-May-22 19:08:58 - DEBUG - <module>:18 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
06-May-22 19:08:58 - DEBUG - <module>:20 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
06-May-22 19:08:58 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
06-May-22 19:22:12 - INFO - getCode:60 - Querying for code
06-May-22 19:22:12 - INFO - getCode:63 - Successfully retrieved code
06-May-22 19:22:12 - INFO - getCode:66 - Querying for access token
06-May-22 19:22:12 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
06-May-22 19:22:14 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/oauth/token HTTP/1.1" 200 None
06-May-22 19:22:14 - INFO - getCode:70 - Successfully retrieved access token using code
06-May-22 19:22:14 - INFO - getCode:77 - Querying for database ID
06-May-22 19:22:14 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
06-May-22 19:22:15 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/search HTTP/1.1" 200 None
06-May-22 19:22:15 - INFO - getCode:80 - Database ID retrieved
06-May-22 19:22:15 - ERROR - log_exception:1455 - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sravanthis/Documents/ReadingList/server/virt/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 85, in getCode
    addToDatabase(tokenDetails, database_id)
  File "/Users/sravanthis/Documents/ReadingList/server/publicInteg.py", line 23, in addToDatabase
    cursor_object = conn.cursor()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4564059648 and this is thread id 123145411678208.
06-May-22 19:22:15 - INFO - _log:224 - 127.0.0.1 - - [06/May/2022 19:22:15] "[35m[1mGET /?code=e809557e-32e9-424c-9cb6-c6f0cb6edd39&state= HTTP/1.1[0m" 500 -
06-May-22 19:32:15 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
06-May-22 19:33:15 - INFO - getCode:60 - Querying for code
06-May-22 19:33:15 - INFO - getCode:63 - Successfully retrieved code
06-May-22 19:33:15 - INFO - getCode:66 - Querying for access token
06-May-22 19:33:15 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
06-May-22 19:33:16 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/oauth/token HTTP/1.1" 200 None
06-May-22 19:33:16 - INFO - getCode:70 - Successfully retrieved access token using code
06-May-22 19:33:16 - INFO - getCode:77 - Querying for database ID
06-May-22 19:33:16 - DEBUG - _new_conn:1001 - Starting new HTTPS connection (1): api.notion.com:443
06-May-22 19:33:17 - DEBUG - _make_request:456 - https://api.notion.com:443 "POST /v1/search HTTP/1.1" 200 None
06-May-22 19:33:17 - INFO - getCode:80 - Database ID retrieved
06-May-22 19:33:17 - DEBUG - addToDatabase:20 - Connecting to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
06-May-22 19:33:17 - DEBUG - addToDatabase:22 - Connected to database file '/Users/sravanthis/Documents/ReadingList/notionReadingList.db
06-May-22 19:33:17 - INFO - addToDatabase:33 - Successfully retrieved access token from dictionary for user bf0d816a-d155-4be4-bc24-3b7920af878d
06-May-22 19:33:17 - INFO - _log:224 - 127.0.0.1 - - [06/May/2022 19:33:17] "GET /?code=cc71eab3-1e2f-45ef-b1e6-cf63b83a287e&state= HTTP/1.1" 200 -
06-May-22 19:33:18 - INFO - _log:224 - 127.0.0.1 - - [06/May/2022 19:33:18] "GET /static/Se7enForward.svg HTTP/1.1" 200 -
06-May-22 19:38:26 - INFO - _log:224 - 127.0.0.1 - - [06/May/2022 19:38:26] "GET /home HTTP/1.1" 200 -
06-May-22 19:38:26 - INFO - _log:224 - 127.0.0.1 - - [06/May/2022 19:38:26] "[36mGET /static/Se7enForward.svg HTTP/1.1[0m" 304 -
06-May-22 19:38:39 - INFO - _log:224 - 127.0.0.1 - - [06/May/2022 19:38:39] "GET /terms HTTP/1.1" 200 -
06-May-22 19:38:47 - INFO - _log:224 - 127.0.0.1 - - [06/May/2022 19:38:47] "GET /privacy HTTP/1.1" 200 -
08-May-22 18:25:24 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
08-May-22 18:25:26 - INFO - _log:224 - 127.0.0.1 - - [08/May/2022 18:25:26] "GET /home HTTP/1.1" 200 -
08-May-22 18:25:26 - INFO - _log:224 - 127.0.0.1 - - [08/May/2022 18:25:26] "GET /static/Se7enForward.svg HTTP/1.1" 200 -
08-May-22 18:28:34 - INFO - _log:224 -  * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
08-May-22 18:28:38 - INFO - _log:224 - 127.0.0.1 - - [08/May/2022 18:28:38] "GET /home HTTP/1.1" 200 -
08-May-22 18:28:38 - INFO - _log:224 - 127.0.0.1 - - [08/May/2022 18:28:38] "[36mGET /static/Se7enForward.svg HTTP/1.1[0m" 304 -
